//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RVP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BOSEMEntities : DbContext
    {
        public BOSEMEntities()
            : base("name=BOSEMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TransactionHistory> TransactionHistories { get; set; }
        public virtual DbSet<hslc> hslcs { get; set; }
        public virtual DbSet<requested_mark> requested_mark { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<RequestHistories> RequestHistories { get; set; }
        public virtual DbSet<SubjectYearCombinations> SubjectYearCombinations { get; set; }
        public virtual DbSet<SubjectFields> SubjectFields { get; set; }
    }
}
