//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RVP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hslc
    {
        public int id { get; set; }
        public int roll { get; set; }
        public string name { get; set; }
        public string sex_code { get; set; }
        public string opt1 { get; set; }
        public string opt2 { get; set; }
        public string school { get; set; }
        public string regu { get; set; }
        public Nullable<int> mil_ext { get; set; }
        public Nullable<int> falt1 { get; set; }
        public Nullable<int> falt2 { get; set; }
        public Nullable<int> at { get; set; }
        public Nullable<int> eng_ext { get; set; }
        public Nullable<int> math_total { get; set; }
        public Nullable<int> sc_total { get; set; }
        public Nullable<int> ssc_ext { get; set; }
        public Nullable<int> lg { get; set; }
        public Nullable<int> ag { get; set; }
        public Nullable<int> eg { get; set; }
        public Nullable<int> mg { get; set; }
        public Nullable<int> scg { get; set; }
        public Nullable<int> ssg { get; set; }
        public Nullable<int> tg { get; set; }
        public Nullable<int> tc { get; set; }
        public Nullable<int> total { get; set; }
        public Nullable<int> addl_ext { get; set; }
        public Nullable<int> excess { get; set; }
        public Nullable<int> gtotal { get; set; }
        public Nullable<int> divi { get; set; }
        public string asub { get; set; }
        public Nullable<decimal> exm_year { get; set; }
        public Nullable<decimal> exm_month { get; set; }
        public Nullable<decimal> fk_school_cd { get; set; }
        public string prn_no { get; set; }
        public string caste { get; set; }
        public Nullable<int> sct_sec1 { get; set; }
        public Nullable<int> sct_sec2 { get; set; }
        public Nullable<int> sct_sec3 { get; set; }
        public Nullable<int> ssct_sec1 { get; set; }
        public Nullable<int> ssct_sec2 { get; set; }
        public Nullable<int> ssct_sec3 { get; set; }
        public Nullable<int> sc_int { get; set; }
        public Nullable<int> math_int { get; set; }
        public Nullable<int> math_ext { get; set; }
        public Nullable<int> sc_ext { get; set; }
        public Nullable<int> mil_int { get; set; }
        public Nullable<int> mil_total { get; set; }
        public Nullable<int> eng_int { get; set; }
        public Nullable<int> eng_total { get; set; }
        public Nullable<int> ssc_int { get; set; }
        public Nullable<int> ssc_total { get; set; }
        public Nullable<int> addl_int { get; set; }
        public Nullable<int> addl_total { get; set; }
        public Nullable<int> phe { get; set; }
        public Nullable<int> we { get; set; }
        public Nullable<int> Th1 { get; set; }
        public Nullable<int> Th2 { get; set; }
        public Nullable<int> Pr1 { get; set; }
        public Nullable<int> Pr2 { get; set; }
        public string dob { get; set; }
        public string father_name { get; set; }
        public string mother_name { get; set; }
    }
}
