//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RVP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentRates
    {
        public System.DateTime created_at { get; set; }
        public decimal amount { get; set; }
        public string order_no { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public string created_by { get; set; }
        public string id { get; set; }
    }
}
