//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RVP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestHistories
    {
        public string id { get; set; }
        public System.DateTime request_date { get; set; }
        public string user_id { get; set; }
        public string email { get; set; }
        public string username { get; set; }
        public int exam_result_id { get; set; }
        public Nullable<decimal> exam_year { get; set; }
        public string dob { get; set; }
        public int roll { get; set; }
        public string txn_id { get; set; }
        public string txn_status { get; set; }
        public string payment_status { get; set; }
    }
}
