//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RVP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class requested_mark
    {
        public string id { get; set; }
        public System.DateTime request_date { get; set; }
        public string user_id { get; set; }
        public string payment_status { get; set; }
        public int exam_result_id { get; set; }
        public string txn_id { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual hslc hslc { get; set; }
        public virtual TransactionHistory TransactionHistory { get; set; }
    }
}
