//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RVP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public int sub_code { get; set; }
        public string name { get; set; }
        public string abbrevation { get; set; }
        public Nullable<int> seq_cd { get; set; }
        public string sub_type { get; set; }
        public Nullable<int> include_in_total { get; set; }
        public Nullable<int> year { get; set; }
        public int id { get; set; }
    }
}
