//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RVP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Subject
    {
        [Required]
        [Display(Name = "Subject Code")]
        public int sub_code { get; set; }

        [Required]
        [Display(Name = "Subject Name")]
        public string name { get; set; }

        [Required]
        [Display(Name = "Abbrevation")]
        public string abbrevation { get; set; }

        [Required]
        [Display(Name = "Sequence Code")]
        public Nullable<int> seq_cd { get; set; }

        [Required]
        [Display(Name = "Subject Type / Study Flag")]
        public string sub_type { get; set; }
        public int id { get; set; }
    }
}
