//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RVP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectFields
    {
        public string id { get; set; }
        public int sub_year_id { get; set; }
        public string field_name { get; set; }
        public string field_meaning { get; set; }
        public Nullable<int> pass_mark { get; set; }
        public Nullable<int> full_mark { get; set; }
        public int field_seq { get; set; }
    
        public virtual SubjectYearCombinations SubjectYearCombinations { get; set; }
    }
}
